name: Auto Build Scanner
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutu
        uses: actions/checkout@master

      - name: set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: temurin

      - name: gen JKS File
        run: echo $ENCODED_KEYSTORE | base64 -di > app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      #      - name: Get commit SHA
      #        id: get_commit_sha
      #        run: 'echo ::set-output name=VERSION::-{GITHUB_SHA: 0: 6}'

      - name: Build APK with Gradle (DEV)
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NAME_SUFFIX: '.dev'

      - name: Build APK with Gradle (MAIN)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NAME_SUFFIX: ''
        #          NAME_SUFFIX: ${{ steps.get_commit_sha.outputs.VERSION }}

      - name: Upload Released APK armv7
        uses: actions/upload-artifact@v2
        with:
          name: scanner-armv7
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Upload Released APK armv8
        uses: actions/upload-artifact@v2
        with:
          name: scanner-armv8
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload Released APK x86
        uses: actions/upload-artifact@v2
        with:
          name: scanner-x86
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Upload Released APK x86_64
        uses: actions/upload-artifact@v2
        with:
          name: scanner-x86_64(wsa)
          path: app/build/outputs/apk/release/app-x86_64-release.apk

      - name: Upload File to Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            app/build/outputs/apk/release/app-arm64-v8a-release.apk
            app/build/outputs/apk/release/app-x86-release.apk
            app/build/outputs/apk/release/app-x86_64-release.apk
          body: Released By Action
          generate_release_notes: true