name: Auto Build Scanner
on:
  create:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'

      #      - name: Gradle Cache
      #        uses: actions/cache@v3
      #        with:
      #          path: |
      #            ~/.gradle/caches
      #            ~/.gradle/wrapper
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #          restore-keys: |
      #            ${{ runner.os }}-gradle-

      - name: gen JKS File
        run: echo $ENCODED_KEYSTORE | base64 -di > app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      #      - name: Get commit SHA
      #        id: get_commit_sha
      #        run: 'echo ::set-output name=VERSION::-{GITHUB_SHA: 0: 6}'

      - name: Build APK with Gradle (DEV)
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NAME_SUFFIX: '.dev'
        run: |
          chmod +x gradlew
          ./gradlew build


      - name: Build APK with Gradle (MAIN)
        if: ${{ github.ref != 'refs/heads/dev' }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NAME_SUFFIX: ''
        #          NAME_SUFFIX: ${{ steps.get_commit_sha.outputs.VERSION }}
      
      # - name: Build File Check
      #   run: |
      #     cd app/build/outputs/apk/release/
      #     ls

#      - name: Upload Released APK armv7
#        uses: actions/upload-artifact@v3
#        with:
#          name: scanner-armv7
#          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Upload Released APK armv8
        uses: actions/upload-artifact@v3
        with:
          name: scanner-armv8
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      #      - name: Upload Released APK x86_64
      #        uses: actions/upload-artifact@v2
      #        with:
      #          name: scanner-x86_64(wsa)
      #          path: app/build/outputs/apk/release/app-x86_64-release.apk

      - name: Upload Released APK x86
        uses: actions/upload-artifact@v3
        with:
          name: scanner-x86 (Emulator)
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Upload Released Universal APK
        uses: actions/upload-artifact@v3
        with:
          name: scanner-universal
          path: app/build/outputs/apk/release/app-universal-release.apk

      - name: Upload APKs to Release Page
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            app/build/outputs/apk/release/app-arm64-v8a-release.apk
            app/build/outputs/apk/release/app-x86-release.apk
            app/build/outputs/apk/release/app-universal-release.apk