name: Auto Build Scanner
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutu
        uses: actions/checkout@master

      - name: set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11

      - name: gen JKS File
        run: echo $ENCODED_KEYSTORE | base64 -di > app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.ENCODED_KEYSTORE }}

      #      - name: Get commit SHA
      #        id: get_commit_sha
      #        run: 'echo ::set-output name=VERSION::-{GITHUB_SHA: 0: 6}'

      - name: Build APK with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          NAME_SUFFIX: '.dev'
      #          NAME_SUFFIX: ${{ steps.get_commit_sha.outputs.VERSION }}

      - name: Upload Released APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
